//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArkSpec) DeepCopyInto(out *ArkSpec) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArkSpec.
func (in *ArkSpec) DeepCopy() *ArkSpec {
	if in == nil {
		return nil
	}
	out := new(ArkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeepSeekSpec) DeepCopyInto(out *DeepSeekSpec) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeepSeekSpec.
func (in *DeepSeekSpec) DeepCopy() *DeepSeekSpec {
	if in == nil {
		return nil
	}
	out := new(DeepSeekSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeishuSink) DeepCopyInto(out *FeishuSink) {
	*out = *in
	out.WebhookSecretRef = in.WebhookSecretRef
	out.SignatureSecretRef = in.SignatureSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeishuSink.
func (in *FeishuSink) DeepCopy() *FeishuSink {
	if in == nil {
		return nil
	}
	out := new(FeishuSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeminiSpec) DeepCopyInto(out *GeminiSpec) {
	*out = *in
	out.APIKeySecretRef = in.APIKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeminiSpec.
func (in *GeminiSpec) DeepCopy() *GeminiSpec {
	if in == nil {
		return nil
	}
	out := new(GeminiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KnowledgeBaseSpec) DeepCopyInto(out *KnowledgeBaseSpec) {
	*out = *in
	out.ArkSpec = in.ArkSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KnowledgeBaseSpec.
func (in *KnowledgeBaseSpec) DeepCopy() *KnowledgeBaseSpec {
	if in == nil {
		return nil
	}
	out := new(KnowledgeBaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kopilot) DeepCopyInto(out *Kopilot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kopilot.
func (in *Kopilot) DeepCopy() *Kopilot {
	if in == nil {
		return nil
	}
	out := new(Kopilot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kopilot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopilotList) DeepCopyInto(out *KopilotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kopilot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopilotList.
func (in *KopilotList) DeepCopy() *KopilotList {
	if in == nil {
		return nil
	}
	out := new(KopilotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KopilotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopilotSpec) DeepCopyInto(out *KopilotSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.LogSource.DeepCopyInto(&out.LogSource)
	out.LLM = in.LLM
	in.Notification.DeepCopyInto(&out.Notification)
	if in.KnowledgeBase != nil {
		in, out := &in.KnowledgeBase, &out.KnowledgeBase
		*out = new(KnowledgeBaseSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopilotSpec.
func (in *KopilotSpec) DeepCopy() *KopilotSpec {
	if in == nil {
		return nil
	}
	out := new(KopilotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KopilotStatus) DeepCopyInto(out *KopilotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KopilotStatus.
func (in *KopilotStatus) DeepCopy() *KopilotStatus {
	if in == nil {
		return nil
	}
	out := new(KopilotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMSpec) DeepCopyInto(out *LLMSpec) {
	*out = *in
	out.Gemini = in.Gemini
	out.DeepSeek = in.DeepSeek
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMSpec.
func (in *LLMSpec) DeepCopy() *LLMSpec {
	if in == nil {
		return nil
	}
	out := new(LLMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSourceSpec) DeepCopyInto(out *LogSourceSpec) {
	*out = *in
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(LokiSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSourceSpec.
func (in *LogSourceSpec) DeepCopy() *LogSourceSpec {
	if in == nil {
		return nil
	}
	out := new(LogSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiSource) DeepCopyInto(out *LokiSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiSource.
func (in *LokiSource) DeepCopy() *LokiSource {
	if in == nil {
		return nil
	}
	out := new(LokiSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSink) DeepCopyInto(out *NotificationSink) {
	*out = *in
	if in.Feishu != nil {
		in, out := &in.Feishu, &out.Feishu
		*out = new(FeishuSink)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSink.
func (in *NotificationSink) DeepCopy() *NotificationSink {
	if in == nil {
		return nil
	}
	out := new(NotificationSink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.Sinks != nil {
		in, out := &in.Sinks, &out.Sinks
		*out = make([]NotificationSink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationSpec.
func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}
