# This rule is not used by the project kopilot itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kopilot.fl0rencess720.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kopilot
    app.kubernetes.io/managed-by: kustomize
  name: kopilot-editor-role
rules:
- apiGroups:
  - kopilot.fl0rencess720
  resources:
  - kopilots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kopilot.fl0rencess720
  resources:
  - kopilots/status
  verbs:
  - get
